### PR TITLE
old shoe

### PR DESCRIPTION
**Pull request by maxmarzolf**
3 lines bruh

### CODE REVIEW

**Comment by Brett-BI** [comment]
Did you want to merge with Anubis or have it be its own thing?

**Comment by maxmarzolf** [comment]
Doesn't matter, I wonder why it says I modified all the lines, I'm just talking shit.

**Comment by Brett-BI** [comment]
Looking at it on mobile. Doesn't say you modified everything but the line count is high because of that .csv.

**Comment by maxmarzolf** [comment]
Oh word, good call

**Pull request closed without merging**
